development:
    :rt:
        :adapter: mysql2
        :host: 'smspike.ccaxw0t5omeg.us-east-1.rds.amazonaws.com'
        :database: 'rt'
        :user: 'db_admin'
        :password: 'qwedsa123'
    :dirt:
        :adapter: sqlite
        :database: './db/dirt.db'
test:
production:
